name: OSX
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # We build RelProfile to test both Release and Profiling aspects of the build
  BUILD_TYPE: RelProfile

jobs:
  mac_os_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-10.15, macos-11, macos-12 ]
        generator: [ Xcode, Unix Makefiles ]
        xcode-version: [ latest-stable ]
        # From 12.1 to 12.4 (inclusive), all XCode versions use the same
        # compiler version.

        include:
          - os: macos-10.15
            xcode-version: 12.4
          - os: macos-11
            xcode-version: 13.0
          - os: macos-11
            xcode-version: 13.1
          - os: macos-12
            xcode-version: 13.1
          - os: macos-12
            xcode-version: 13.2
    
    name: ${{ matrix.os }} (XCode ${{ matrix.xcode-version }}, ${{ matrix.generator }} Generator)

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-xcode-${{ matrix.xcode-version }}
          max-size: 100M
            
      - name: Configure CMake
        run: |
          cmake -B${{ github.workspace }}/build \
                -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                -G${{ matrix.generator }}

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build \
                --config ${{ env.BUILD_TYPE }} \
                --target Editor Test \
                -- -j2
